### ISSUE TITLE
Typo on image url of Kim Wexler character

### ISSUE THREAD

**Issue by waleska404** [renatoka/better-call-saul-api#2]
**Describe the bug**
There is a typo in the image URL of Kim Wexler character. 

**To Reproduce**
1. Make an API call to: https://bettercallsaul-api.onrender.com/characters
2. See character 3 image url

**Expected behavior**
The link has double 'h' on HTTPs. It shows like hhttps... when it should be http...

**Screenshots**
![image](https://user-images.githubusercontent.com/26300667/225709887-4a9bb67f-2d94-430e-a601-b2279981b761.png)

**Comment by renatoka** [comment]
Thank you for pointing this out @waleska404.
I'm rewriting this API to work on Nest.js and have solved this issue.
